-   id: checkov
    name: Checkov
    description: This hook runs checkov.
    entry: checkov
    language: python
    pass_filenames: false
    always_run: false
    files: \.tf$
    exclude: \.+.terraform\/.*$
    require_serial: true
